### ISSUE TITLE
How is ground truth derived? 

### ISSUE THREAD

**Issue by adelinawong** [JonathonLuiten/TrackEval#122]
Would like to know how does ground truth come about for the MOT challenge benchmark. Is the ground truth manually labelled or is it run against a certain tracker and the result becomes the ground truth? Thank you and hope to hear from you soon!

**Comment by gehadza** [comment]
Did you know about ground truth ?

**Comment by chumpblocckami** [comment]
@adelinawong  According to the [MOT16 paper](https://arxiv.org/pdf/1603.00831.pdf) and [MOT 20 paper](https://arxiv.org/pdf/2003.09003.pdf), the ground truth is manually labeled. 
Check other papers and resources [here](https://motchallenge.net/faq/).
Happy coding!

**Comment by JonathonLuiten** [comment]
yup it has been manually labelled.
