### ISSUE TITLE
How are 2d bounding boxes labeled in kitti ?

### ISSUE THREAD

**Issue by kshashankrao** [JonathonLuiten/TrackEval#136]
Are the 2d bounding boxes creating using the 3d bounding boxes that is labeled in the point cloud ?
If so, could you please provide the code/logic for this transformation.

**Comment by JonathonLuiten** [comment]
yes, they are 'amodal'. E.g. 3D boxes were fit to the obejct point clouds in 3D, and then these 3D boxes were projected from 3D into 2D
