### ISSUE TITLE
The difference between MOT and MOTS evaluation on HOTA metrcis 

### ISSUE THREAD

**Issue by NanH5837** [JonathonLuiten/TrackEval#137]
I want to evaluate on custom dataset. Due to the difficulty of segmentation mask labeling, can I only label bounding boxes and only obtain the bounding boxes output by the MOTS algorithm for the HOTA metrics evaluation. Is there a big difference between this(using bounding boxes) and the evaluation of HOTA metrics using masks? Here the HOTA metrics only refer to association scores such as AssA, AssPr and AssRe. Thank you!

**Comment by JonathonLuiten** [comment]
you can evaluate boxes or segmentation masks the same without any issue.
