### ISSUE TITLE
how to calculate HOTA for DeepSORT?

### ISSUE THREAD

**Issue by tianyufang1958** [JonathonLuiten/TrackEval#138]
As DeepSORT doesn't use IOU as matching criteria, i am just wondering how HOTA was calculated for DeepSORT? Thanks so much.

**Comment by JonathonLuiten** [comment]
You should calculate HOTA for DeepSORT or any method the EXACT SAME way, so that the metric is comparable between methods. Thus you can fairly compare methods.
