### ISSUE TITLE
Too Low HOTA and IDF1

### ISSUE THREAD

**Issue by H1-KEY** [JonathonLuiten/TrackEval#146]
Hi, I'm trying to test on my custom dataset. 
However, HOTA and IDF1 scores are too low. 
What do you think I should check?

![image](https://github.com/JonathonLuiten/TrackEval/assets/163990061/699a57a0-dcd2-4dcf-a144-0346412e0500)

Thanks.

**Comment by JonathonLuiten** [comment]
There is not enough information here to help sorry. Why do you think they are too low?

**Comment by lmaple24327** [comment]
> Hi, I'm trying to test on my custom dataset. However, HOTA and IDF1 scores are too low. What do you think I should check?
> 
> ![image](https://private-user-images.githubusercontent.com/163990061/326379993-699a57a0-dcd2-4dcf-a144-0346412e0500.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzkyNzEsIm5iZiI6MTczMzQ3ODk3MSwicGF0aCI6Ii8xNjM5OTAwNjEvMzI2Mzc5OTkzLTY5OWE1N2EwLWRjZDItNGRjZi1hMTQ0LTAzNDY0MTJlMDUwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwOTU2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODhhOTJlOWY5M2Q5MTdjYjg5NTZhNGMwNDNjNzNkMjhjODA4NDVlZGVjZjVjYTUwMTVlMjliMzg3ZTk0ZDdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._WbSOpAlKfqVz0WCv5rGJN9XG_kRXv7TQBH9TQi-DEI)
> 
> Thanks.

Hello, may I ask if you have solved this problem

**Comment by H1-KEY** [comment]
> > Hi, I'm trying to test on my custom dataset. However, HOTA and IDF1 scores are too low. What do you think I should check?
> > ![image](https://private-user-images.githubusercontent.com/163990061/326379993-699a57a0-dcd2-4dcf-a144-0346412e0500.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzkyNzEsIm5iZiI6MTczMzQ3ODk3MSwicGF0aCI6Ii8xNjM5OTAwNjEvMzI2Mzc5OTkzLTY5OWE1N2EwLWRjZDItNGRjZi1hMTQ0LTAzNDY0MTJlMDUwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwOTU2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODhhOTJlOWY5M2Q5MTdjYjg5NTZhNGMwNDNjNzNkMjhjODA4NDVlZGVjZjVjYTUwMTVlMjliMzg3ZTk0ZDdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._WbSOpAlKfqVz0WCv5rGJN9XG_kRXv7TQBH9TQi-DEI)
> > Thanks.
> 
> Hello, may I ask if you have solved this problem

Hi. I found that the annotations are not perfect. So there was the mismatch between detections and ground truths. I think these low scores are normal.
