### ISSUE TITLE
How do we get graphs such as 'AssA bs DetA' ?

### ISSUE THREAD

**Issue by studian** [JonathonLuiten/TrackEval#21]
Like Kitti dashboard, How do we get graphs such as 'AssA bs DetA', 'AssPr vs AssRe', 'DetPr vs DetRe', and 'HOTA(0) vs LocA(0)'?
please, let me know a python script.

**Comment by JonathonLuiten** [comment]
https://github.com/JonathonLuiten/TrackEval/blob/master/scripts/comparison_plots.py
