### ISSUE TITLE
GT not loaded for ai_city data in MOTChallenge format

### ISSUE THREAD

**Issue by JonathonLuiten** [JonathonLuiten/TrackEval#25]
Hi,

Thank you for your great work with the HOTA metrics.
I've a related issue but this is not about the difference between 9 and 10 values per line (even though I tried to remove one to see if it helps, but it does not). 

I tried your script with a GT file from the AICity challenge 2021 and compared it with a pred file they provide, both following the MOT format (attached to this message), but for some unknown reason, the script does not read the GT file, same as if it was empty:

```
Count: DeepSORT-SSD512-pedestrian  Dets      GT_Dets   IDs       GT_IDs
s01-c003                           14151     0         219       0
COMBINED                           14151     0         219       0
```

I tried to change some value, indexed by obj_id instead of frame_id, remove one '-1' at the end of each line, checked the encoding and also checked the entire hierarchy of 'trackers' and 'gt' folders.

Finally, I copied a GT file from a MOT sequence (MOT16-train\MOT16-02) and pasted it as it was my own GT file, even if it doesn't match at all... and it reads the GT file correctly:
```
Count: DeepSORT-SSD512-pedestrian  Dets      GT_Dets   IDs       GT_IDs
s01-c003                           14151     17833     219       54
COMBINED                           14151     17833     219       54
```

Here's the original GT file of the sequence I want to test:
[gt.txt](https://github.com/JonathonLuiten/TrackEval/files/6272112/gt.txt)

Here's one of the prediction file:
[s01-c003.txt](https://github.com/JonathonLuiten/TrackEval/files/6272130/s01-c003.txt)

Thank you in advance for your help.

_Originally posted by @JonathanSamelson in https://github.com/JonathonLuiten/TrackEval/issues/23#issuecomment-814948323_

**Comment by JonathanSamelson** [comment]
Indeed, it's working good now! Thank you!
