### ISSUE TITLE
MOT Test Data

### ISSUE THREAD

**Issue by kameel2311** [JonathonLuiten/TrackEval#26]
Thank you very much for the code and data packages, I was wondering if the Test data for the MOT Benchmarks are available ? And how to adapt the code to run only one sequence of one benchmark of one tracker ?

**Comment by JonathonLuiten** [comment]
The 'test images' are avaliable on https://motchallenge.net/. The test gt is not avaliable, but you can evaluate your methods against it by uploading them to be evaluated on https://motchallenge.net/.

To only run on certain sequences you can use the flag ```SEQ_INFO```. E.g. using all the flags below allow you to specify the sequences, benchmark, and trackers. 

```--SEQ_INFO MOT16-02 MOT16-04 --BENCHMARK MOT16 --SPLIT_TO_EVAL train --TRACKERS_TO_EVAL MPNTrack --METRICS HOTA CLEAR Identity VACE```

This answers your questions so closing his now.
