### ISSUE TITLE
conf value and det.txt what are they? 

### ISSUE THREAD

**Issue by Rajkumarsaswamy** [JonathonLuiten/TrackEval#28]
I am trying to understand what format my tracker output should be: 

in 1. its confusing for me, conf and what is det.txt and in 2. here conf value is -1. 

my question, in my tracker output do i print conf as -1 ? and what does this statement mean? "The conf value contains the detection confidence in the det.txt files." i am aware that my detector can produce txt files with confidence value. so in the tracker output i don't print conf value and make it -1 and let my detector print conf value?

1. 

frame, id, bb_left, bb_top, bb_width, bb_height, conf, x, y, z
The conf value contains the detection confidence in the det.txt files.

2. 
Tracking with bounding boxes
(MOT15, MOT16, MOT17, MOT20)
  1, 3, 794.27, 247.59, 71.245, 174.88, -1, -1, -1, -1
  1, 6, 1648.1, 119.61, 66.504, 163.24, -1, -1, -1, -1
  1, 8, 875.49, 399.98, 95.303, 233.93, -1, -1, -1, -1
  ...

**Comment by JonathonLuiten** [comment]
the confidence values are ignored for detection evaluation for most metrics (HOTA, CLEAR, Identity etc). Some metrics use them e.g. Track mAP. So feel free to leave them or set to -1. It doesn't matter.

The reason they are in the det files, is that these confidences are usually extremely useful to decide which detections to keep and which to remove, but yes, they are usually ignored for evaluation (for most metrics).
