### ISSUE TITLE
HOTA for Multi Camera

### ISSUE THREAD

**Issue by ATrackerLearner** [JonathonLuiten/TrackEval#31]
Hi, Thanks for the code, it works like a charm for mono-camera.

I would like to compute HOTA for multi camera dataset (let's say we have 2 seqs corresponding to camera 1 and camera 2 sequence). What should I do?

I had some ideas like :

- each camera sequence as an independant sequence (like 2 mono camera sequence)
- do one sequence which is the concatenation of both sequence ?
- Simultaneously sequence 1 and sequence 2 on the same .txt. Like 1 ID appears on two frames.

I think option 3 would definetely messus up with HOTA computation.
I think that option 1 and 2 would work but would it take in consideration that one ID is the same per frame accross all cameras. I mean if I have an ID_1 on frame 1 on both camera then it takes in consideration it is ID_1 on both camera and not ID_1 and ID_2 for exemple.
We could have a situation like : ID_1 and ID_2 is perfectly tracked in each camera sequence but my tracking advice would still label two differents IDs for the same ID across camera ... 

That would be to use HOTA for Person-Reidentification task as Market1501 dataset and so on. In the article it says that HOTA can be easily extended for multi camera, I am curious about this extension and I am sorry if the answer is trivial.

I hope this is clearn and thanks again for your amazing work.

**Comment by JonathonLuiten** [comment]
Hey!

Thanks for your question. I haven't thought about or looked into the multi-camera case myself. So I am also not 100% sure what people do there.

I think (although I am not sure), that if you want the IDs to be consistent across different cameras (I assume you do), then simply multiplying the number of timesteps by the number of cameras by effectively adding all of the frames together into one file should be fine.

E.g. if we have 100 frames and 3 cameras we can simply map camera 1 onto frames 1-100, camera 2 on 101-200, camera 3 on 201-300. 

Such a method would not work for metrics with MOTA, but I think it works perfectly fine for HOTA.

Try it and let me know if it works for you?

Jono

**Comment by ATrackerLearner** [comment]
Hi,

Thanks for your quick reply, I actually think your solution works, that penalizes ID switches over camera. That was what I meant by "concatenation of both sequence". Awesome!

Mathias.

**Comment by edwardnguyen1705** [comment]
Hi @ATrackerLearner ,
Have you tried it out? Does the "concatenation of both sequence" works?

**Comment by zhengthomastang** [comment]
@ATrackerLearner Do you have a branch of your modification for multi-camera tracking that we could refer to? Thanks so much.
