### ISSUE TITLE
Running eval given two txt files with results

### ISSUE THREAD

**Issue by ferumchrome** [JonathonLuiten/TrackEval#43]
Hello, thanks for your work!

Can I run the evaluation having results stored as txt files? I need something like: HOTA = (results.txt, ground_truth.txt). Thanks in advance!

**Comment by goldentimecoolk** [comment]
Hi @amoskalev, have you solved the problem? How did you get it?

**Comment by kblittle** [comment]
Hello,I have same questions like you. Do you fix it? Can I get your method about this issue.
