### ISSUE TITLE
MOTS evaluation script 

### ISSUE THREAD

**Issue by VladimirYugay** [JonathonLuiten/TrackEval#45]
Hey there,

I've been using your repo for quite a while for MOT challenge. However, I'm facing problems with MOTS challenge. 

I've downloaded the `data` folder to run some simple examples. 

When I run (which is a slight fix of what you've mentioned in the comments in `run_mots_challenge.py`)
`python scripts/run_mots_challenge.py --USE_PARALLEL False --METRICS HOTA --TRACKERS_TO_EVAL track_rcnn`

I'm getting the following error:

`
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
`

**Comment by ATrackerLearner** [comment]
Hey,

I got the same problem, you need to install a newer version of numpy to fix this error as pointed in this Issue #38 https://github.com/JonathonLuiten/TrackEval/issues/38#issuecomment-842125160. You will have this error in any MOTS datasetsif you don't update numpy.

**Comment by JonathonLuiten** [comment]
@ATrackerLearner thanks for answering. I agree this sounds like an error with old numpy versions.

@VladimirYugay could you try update numpy, see if that fixes everything and if so I guess this can be closed.
