### ISSUE TITLE
error on MOT evaluation using run_mot_challenge.py

### ISSUE THREAD

**Issue by atousaz** [JonathonLuiten/TrackEval#72]
Hello ,
Im getting following error with this command
!python scripts/run_mot_challenge.py --DO_PREPROC False --BENCHMARK MOT20-train

raise TrackEvalException('no seqmap found: ' + os.path.basename(seqmap_file))
trackeval.utils.TrackEvalException: no seqmap found: MOT20-train-train.txt

Looking forward to your respond

**Comment by siiigrid** [comment]
How did you solve it?
I have the same problem and I'm looking for an answer.

**Comment by Manan1602** [comment]
Hey @siiigrid did you figure out a work around? I'm facing the same issue.
One of us for every year ig?😅

**Comment by ramafahad** [comment]
hi everyone, any updates on how to fix it?
