### ISSUE TITLE
Low HOTA metrics and Identity Metrics

### ISSUE THREAD

**Issue by HamletMonkey** [JonathonLuiten/TrackEval#79]
![image](https://user-images.githubusercontent.com/85542530/165483750-e675c12e-adb4-481d-a7e9-7a197ba9e8ca.png)
I've gotten low HOTA metrics (around 10-11) and Identity metrics (iDF1 around 7-8) using both TraDes and TransTrack method, for MOT17 half val dataset. Any idea how could I solve this?

My tracker text file
![image](https://user-images.githubusercontent.com/85542530/165484548-520bb11e-736e-4369-a37a-60fc624fa721.png)

**Comment by HamletMonkey** [comment]
I'm good now.

**Comment by dodeokwangyooo** [comment]
my hota is low too.  How do you solve your problem

**Comment by lmaple24327** [comment]
> my hota is low too. How do you solve your problem

Hello, may I ask if you have solved this problem
